"""empty message

Revision ID: 92090c41312
Revises: None
Create Date: 2014-02-15 18:51:18.374244

"""

# revision identifiers, used by Alembic.
revision = '92090c41312'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mcuser', sa.String(length=16), nullable=True),
    sa.Column('mcemail', sa.String(length=120), nullable=True),
    sa.Column('applicant_age', sa.SmallInteger(), nullable=True),
    sa.Column('applicant_skills', sa.String(), nullable=True),
    sa.Column('applicant_ip', sa.String(length=120), nullable=True),
    sa.Column('fishbanned', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_applicant_ip', 'user', ['applicant_ip'], unique=True)
    op.create_index('ix_user_applicant_skills', 'user', ['applicant_skills'], unique=False)
    op.create_index('ix_user_fishbanned', 'user', ['fishbanned'], unique=False)
    op.create_index('ix_user_mcemail', 'user', ['mcemail'], unique=True)
    op.create_index('ix_user_mcuser', 'user', ['mcuser'], unique=True)
    op.create_table('user_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_application')
    op.drop_index('ix_user_mcuser', table_name='user')
    op.drop_index('ix_user_mcemail', table_name='user')
    op.drop_index('ix_user_fishbanned', table_name='user')
    op.drop_index('ix_user_applicant_skills', table_name='user')
    op.drop_index('ix_user_applicant_ip', table_name='user')
    op.drop_table('user')
    ### end Alembic commands ###
